### ISSUE TITLE
SIGSEGV on series of failed opens

### ISSUE THREAD

**Issue by slfritchie** [basho/eleveldb#100]
NOTE: I haven't made any effort to try to reduce the number of open attempts before the SIGSEGV.  IMHO having such a crash happen at any time is sufficient.  Other random generator seeds crash sooner or later.

Based upon `develop` branch as of fc3f09e5f960930e25649c150c194406a50e5a38

Steps to reproduce on OS X:

```
git checkout f5d7e903960b44dc94db10cb11b68aae83863866
make
rebar skip_deps=true -v eunit suites=XX
make compile_scenarios
./deps/faulterl/ebin/make_intercept_c.escript trigger_commonpaths yo "perl -npi -e 's/bc_fi_enabled = 1/bc_fi_enabled = 0/'"
env `./deps/faulterl/ebin/example_environment.sh yo` erl -pz .eunit deps/*/ebin
```

At this point, you've got an Erlang shell with the LD_PRELOAD magic set up to inject EDQUOT faults when opening files for writing.  ENOSPC does the same thing.

Now, at the shell, run these:

```
[begin Rand = 42, faulterl_nif:poke("bc_fi_random_seed", 0, <<Rand:32>>, false), faulterl_nif:poke("bc_fi_random_reseed", 0, <<1:8>>, false), Rand end || true].
[begin io:format("X = ~p, ", [X]), eunit:test ( iterators ) end || X <- lists:seq ( 1,300 ) ].
```

After the core dump, GDB says that thread 30 has this crazy pointer:

```
(gdb) thread 30
[Switching to thread 30 (core thread 29)]
0x000000001ce9e2e9 in leveldb::Version::~Version (this=0x7f9c02427f00) at db/version_set.cc:98
98        next_->prev_ = prev_;
(gdb) p next_
$1 = ('leveldb::Version' *) 0x6000000000000000
```

**Comment by slfritchie** [comment]
Here's a `beam.smp(17740,0xb3621000) malloc: *** error for object 0x7ff300c23ce0: pointer being freed was not allocated` error in a slighly different place, when using a different seed.

```
(gdb) where
#0  0x000000001b2f4212 in __pthread_kill ()
#1  0x000000001b186b24 in pthread_kill ()
#2  0x000000001b1caf61 in abort ()
#3  0x000000001b19e989 in free ()
#4  0x0000000026560351 in leveldb::VersionSet::~VersionSet (this=0x7ff300c23660) at db/version_set.cc:463
#5  0x0000000026548d9c in leveldb::DBImpl::~DBImpl (this=0x7ff300c22b60) at db/db_impl.cc:220
#6  0x0000000026548c0f in leveldb::DBImpl::~DBImpl (this=0x7ff300c22b60) at db/db_impl.cc:205
#7  0x0000000026550fa7 in leveldb::DB::Open (options=<value temporarily unavailable, due to optimizations>, dbname=@0x7ff3021011d0, dbptr=0xb3620de0) at db/db_impl.cc:2046
#8  0x000000002654733f in leveldb::Status::ok () at /Users/fritchie/b/src/eleveldb/c_src/leveldb/include/leveldb/status.h:162
#9  0x000000002654733f in eleveldb::OpenTask::operator() (this=0x7ff302101190) at c_src/workitems.cc:164
#10 0x0000000026546873 in eleveldb::eleveldb_thread_pool::notify_caller (work_item=@0x7ff302101190) at c_src/threading.cc:309
#11 0x0000000026546818 in eleveldb::WorkTask::resubmit () at /Users/fritchie/b/src/eleveldb/c_src/workitems.h:373
#12 0x0000000026546818 in eleveldb::eleveldb_write_thread_worker (args=0x7ff302203150) at c_src/threading.cc:374
#13 0x000000001a9c65b5 in erl_drv_thread_wrapper (vdtid=0x248c4f10) at beam/erl_drv_thread.c:117
#14 0x000000001ab639c4 in thr_wrapper (vtwd=0xb10cf988) at pthread/ethread.c:106
#15 0x000000001b185772 in _pthread_start ()
#16 0x000000001b1721a1 in thread_start ()
```

**Comment by matthewvon** [comment]
retry with this: https://github.com/basho/eleveldb/pull/104

**Comment by slfritchie** [comment]
Nope, sorry, I'm still seeing it, with exactly the same stack traces.

**Comment by matthewvon** [comment]
Would you attach or email LOG files from one of the crash runs?

**Comment by slfritchie** [comment]
Yup.

```
2014/03/20-21:11:07.179408 b1873000             Options.comparator: leveldb.InternalKeyComparator
2014/03/20-21:11:07.179435 b1873000      Options.create_if_missing: 1
2014/03/20-21:11:07.179440 b1873000        Options.error_if_exists: 0
2014/03/20-21:11:07.179444 b1873000        Options.paranoid_checks: 0
2014/03/20-21:11:07.179447 b1873000     Options.verify_compactions: 1
2014/03/20-21:11:07.179450 b1873000                    Options.env: 0x7fd363421cd0
2014/03/20-21:11:07.179454 b1873000               Options.info_log: 0x7fd365001100
2014/03/20-21:11:07.179457 b1873000      Options.write_buffer_size: 62914560
2014/03/20-21:11:07.179461 b1873000         Options.max_open_files: 1000
2014/03/20-21:11:07.179464 b1873000            Options.block_cache: 0x7fd365800000
2014/03/20-21:11:07.179467 b1873000             Options.block_size: 4096
2014/03/20-21:11:07.179471 b1873000       Options.block_size_steps: 16
2014/03/20-21:11:07.179474 b1873000 Options.block_restart_interval: 16
2014/03/20-21:11:07.179477 b1873000            Options.compression: 1
2014/03/20-21:11:07.179480 b1873000          Options.filter_policy: NULL
2014/03/20-21:11:07.179484 b1873000              Options.is_repair: false
2014/03/20-21:11:07.179487 b1873000         Options.is_internal_db: false
2014/03/20-21:11:07.179490 b1873000      Options.total_leveldb_mem: 0
2014/03/20-21:11:07.179493 b1873000  Options.block_cache_threshold: 33554432
2014/03/20-21:11:07.179497 b1873000  Options.limited_developer_mem: false
2014/03/20-21:11:07.179500 b1873000       Options.delete_threshold: 1000
2014/03/20-21:11:07.179503 b1873000       Options.fadvise_willneed: false
2014/03/20-21:11:07.179506 b1873000                         crc32c: hardware
2014/03/20-21:11:07.179509 b1873000                File cache size: 186646528
2014/03/20-21:11:07.179513 b1873000               Block cache size: 188743680
```

**Comment by matthewvon** [comment]
so the eleveldb issue #100 is freezing just opening and closing the database, no real activity ... so problem is therefore in forced failure of one of the main files ... manifest, log, or LOG ... hmm …

Ok.  May I have a directory listing of the failed vnode?

**Comment by matthewvon** [comment]
Notes from Scott on error injection rates:

access(2) is injected 100% of the time with ELOOP.
flock(2) is injected 80% of the time with EBADF if certain bits are set.
open(2) is injected 50% of the time with EDQUOT
unlink(2) is injected 100% of the time with ENOSPC
unlinkat(2) is injected 100% of the time with ENOSPC

**Comment by matthewvon** [comment]
see branch mv-mutex-assert … fix added there (and debug build warning addressed).

**Comment by matthewvon** [comment]
oops:  mv-mutex-assert on LEVELDB branch, not eleveldb

**Comment by slfritchie** [comment]
Yes, it looks like https://github.com/basho/leveldb/pull/125 prevents this crash: I see 3K iterations without any crash, yay.
